src/main/java/uk/gov/companieshouse/filevalidationservice/controllers/CsvValidationController.java, src/main/java/uk/gov/companieshouse/filevalidationservice/service/FileTransferService.java, src/main/resources/application.properties, src/test/java/uk/gov/companieshouse/filevalidationservice/controllers/CsvValidationControllerTest.java, src/test/java/uk/gov/companieshouse/filevalidationservice/service/FileTransferServiceTest.java
=> IDVA5-1290-uploadFile

terraform/groups/ecs-service/data.tf, terraform/groups/ecs-service/locals.tf, terraform/groups/ecs-service/main.tf
=> lb changes for internalapi

src/main/resources/application.properties
set config for max file size
https://companieshouse.atlassian.net/browse/IDVA5-1565
=> set config for max file size

pom.xml, src/main/java/uk/gov/companieshouse/filevalidationservice/controllers/CsvValidationController.java, src/main/java/uk/gov/companieshouse/filevalidationservice/controllers/FileSizeExceptionAdvice.java, src/main/java/uk/gov/companieshouse/filevalidationservice/models/FileMetaData.java, src/main/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessor.java, src/main/java/uk/gov/companieshouse/filevalidationservice/service/FileTransferService.java, src/test/java/uk/gov/companieshouse/filevalidationservice/controllers/CsvValidationControllerTest.java, src/test/java/uk/gov/companieshouse/filevalidationservice/service/FileTransferServiceTest.java
=> IDVA5-1588-modifyUpdateFileEndpoint

pom.xml, src/main/java/uk/gov/companieshouse/filevalidationservice/configuration/ShedLockConfig.java, src/main/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessor.java, src/main/java/uk/gov/companieshouse/filevalidationservice/service/ValidationScheduler.java, src/main/resources/application.properties, src/test/java/uk/gov/companieshouse/filevalidationservice/configuration/ShedLockConfigTest.java, src/test/resources/application.properties
Added code to avoid race condition from multiple instances.
https://companieshouse.atlassian.net/browse/IDVA5-1591
=> used shedLock to avoid race condition

terraform/groups/ecs-service/iam.tf, terraform/groups/ecs-service/main.tf
=> Adding Task Role

src/main/java/uk/gov/companieshouse/filevalidationservice/models/FileValidation.java, src/main/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessor.java, src/main/java/uk/gov/companieshouse/filevalidationservice/repositories/FileValidationRepository.java, src/main/java/uk/gov/companieshouse/filevalidationservice/service/ValidationScheduler.java, src/test/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessorTest.java, src/test/java/uk/gov/companieshouse/filevalidationservice/service/ValidationSchedulerTest.java
Adding error messages to Mongodb when an error occurs in processing csv during ValidationScheduler
IDVA5-1628
=> Adding error messages to Mongodb when an error occurs

src/main/java/uk/gov/companieshouse/filevalidationservice/controllers/CsvValidationController.java, src/main/java/uk/gov/companieshouse/filevalidationservice/service/FileTransferService.java, src/test/java/uk/gov/companieshouse/filevalidationservice/controllers/CsvValidationControllerTest.java, src/test/java/uk/gov/companieshouse/filevalidationservice/controllers/FileSizeExceptionAdviceTest.java, src/test/java/uk/gov/companieshouse/filevalidationservice/service/FileTransferServiceTest.java
=> IDVA5-1634 improve test coverage

src/main/java/uk/gov/companieshouse/filevalidationservice/configuration/MongoConfig.java, src/main/java/uk/gov/companieshouse/filevalidationservice/configuration/ValidatorConfig.java, src/main/java/uk/gov/companieshouse/filevalidationservice/service/CsvValidationService.java, src/main/resources/application.properties
Removed unused files and added snake case naming strategy for Mongo
IDVA5-1638
=> Removed unused files and added snake case naming strategy for Mongo

pom.xml, src/main/java/uk/gov/companieshouse/filevalidationservice/controllers/CsvValidationController.java, src/test/java/uk/gov/companieshouse/filevalidationservice/controllers/CsvValidationControllerTest.java
=> Idva5 1588 improve validation

src/main/java/uk/gov/companieshouse/filevalidationservice/rest/S3UploadClient.java
console logging secret key and access key
=> console logging secret key and access key

src/main/java/uk/gov/companieshouse/filevalidationservice/rest/S3UploadClient.java
=> removing log statements

src/main/java/uk/gov/companieshouse/filevalidationservice/utils/Constants.java, src/test/resources/oneGoodRecord.csv
=> IDVA5-1653 Fix unique Id format

pom.xml, suppress.xml
=> updated versions for vulnerabilities

src/main/java/uk/gov/companieshouse/filevalidationservice/validation/CsvRecordValidator.java, src/test/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessorTest.java, src/test/resources/good_multiple_records.csv
fix empty date of birth issue
https://companieshouse.atlassian.net/browse/IDVA5-1655
=> fix empty date of birth issue

src/main/java/uk/gov/companieshouse/filevalidationservice/models/FileStatus.java, src/main/java/uk/gov/companieshouse/filevalidationservice/models/FileValidation.java, src/main/java/uk/gov/companieshouse/filevalidationservice/repositories/FileValidationRepository.java, src/main/java/uk/gov/companieshouse/filevalidationservice/rest/S3UploadClient.java, src/main/java/uk/gov/companieshouse/filevalidationservice/service/FileTransferService.java, src/main/java/uk/gov/companieshouse/filevalidationservice/service/ValidationScheduler.java, src/test/java/uk/gov/companieshouse/filevalidationservice/rest/S3UploadClientTest.java, src/test/java/uk/gov/companieshouse/filevalidationservice/service/FileTransferServiceTest.java, src/test/java/uk/gov/companieshouse/filevalidationservice/service/ValidationSchedulerTest.java
Updating validation to only call db once to update status and message.
Added updated-at and updated-by fields to db.
Allowed validator to try again with download and upload errors
IDVA5-1692
=> Code Improvements

src/main/java/uk/gov/companieshouse/filevalidationservice/validation/CsvRecordValidator.java, src/test/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessorTest.java
=> IDVA5-1665 Making unique id nullable

src/main/java/uk/gov/companieshouse/filevalidationservice/service/FileTransferService.java, src/main/java/uk/gov/companieshouse/filevalidationservice/service/ValidationScheduler.java, src/test/java/uk/gov/companieshouse/filevalidationservice/service/FileTransferServiceTest.java, src/test/java/uk/gov/companieshouse/filevalidationservice/service/ValidationSchedulerTest.java
Fixing issue where scheduler does not update the status of a file if it fails for any reason.
Changing file transfer service error so throw download error if file not scanned but AV error if file has a virus.
IDVA5-1703
=> Fixing scheduler issues

src/main/resources/application.properties
=> testing s3 upload issue

src/main/java/uk/gov/companieshouse/filevalidationservice/controllers/CsvValidationController.java, src/test/java/uk/gov/companieshouse/filevalidationservice/controllers/CsvValidationControllerTest.java
=> removed unused endpoint to get files

terraform/groups/ecs-service/iam.tf
=> correcting s3 bucket name

terraform/groups/ecs-service/iam.tf
=> ass s3 permissions

src/main/java/uk/gov/companieshouse/filevalidationservice/repositories/FileValidationRepository.java, src/main/java/uk/gov/companieshouse/filevalidationservice/service/ValidationScheduler.java, src/test/java/uk/gov/companieshouse/filevalidationservice/service/ValidationSchedulerTest.java
Removing error message from file when moved into in-progress status
IDVA5-1724
=> Removing error message from file when moved into in-progress status

src/main/java/uk/gov/companieshouse/filevalidationservice/controllers/CsvValidationController.java, src/test/java/uk/gov/companieshouse/filevalidationservice/controllers/CsvValidationControllerTest.java
Removing mime type check
IDVA5-1736
=> Removing mime type check

src/main/java/uk/gov/companieshouse/filevalidationservice/models/FileStatus.java, src/main/java/uk/gov/companieshouse/filevalidationservice/service/ValidationScheduler.java, src/test/java/uk/gov/companieshouse/filevalidationservice/service/ValidationSchedulerTest.java
=> Fix to update file status in case of generic exception

pom.xml, src/main/java/uk/gov/companieshouse/filevalidationservice/controllers/CsvValidationController.java
Adding Tika to determine the file type
IDVA5-1736
=> Adding Tika to determine the file type

src/main/java/uk/gov/companieshouse/filevalidationservice/controllers/CsvValidationController.java, src/test/java/uk/gov/companieshouse/filevalidationservice/controllers/CsvValidationControllerTest.java
Adding Tika to determine the file type and rejecting if the file is not a csv
IDVA5-1736
=> Adding Tika to determine the file type and rejecting if the file is not a csv

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
=> updating system config

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
=> increasing memory

terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
=> fixing capacity issue for cpu

terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
=> adding live env to profiles

pom.xml, src/main/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessor.java, src/main/java/uk/gov/companieshouse/filevalidationservice/utils/Constants.java, src/test/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessorTest.java, src/test/resources/good_multiple_records_with_case_mismatch_column_names.csv, src/test/resources/good_multiple_records_with_column_names_in_quotes.csv, suppress.xml
make csv headers case-insensitive
https://companieshouse.atlassian.net/browse/IDVA5-1808
=> make csv headers case-insensitive

pom.xml
=> dependency-check issue fix

src/main/java/uk/gov/companieshouse/filevalidationservice/controllers/ControllerAdvice.java, src/test/java/uk/gov/companieshouse/filevalidationservice/configuration/S3ClientConfigTest.java, src/test/java/uk/gov/companieshouse/filevalidationservice/configuration/TikaConfigTest.java, src/test/java/uk/gov/companieshouse/filevalidationservice/controllers/ControllerAdviceTest.java, src/test/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessorTest.java, src/test/java/uk/gov/companieshouse/filevalidationservice/service/ValidationSchedulerTest.java, src/test/resources/application.properties
Adding unit tests to the following files to increase overall test coverage: 
- ControllerAdvice
- S3ClientConfig
- CsvProcessor
- ValidationScheduler
IDVA5-1817
=> Increasing unit test coverage for file-validation-api

pom.xml, src/main/java/uk/gov/companieshouse/filevalidationservice/controllers/CsvValidationController.java, src/main/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessor.java, src/main/java/uk/gov/companieshouse/filevalidationservice/service/ValidationScheduler.java, src/test/java/uk/gov/companieshouse/filevalidationservice/controllers/CsvValidationControllerTest.java, src/test/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessorTest.java, src/test/resources/tooFewColumns.csv, src/test/resources/tooFewHeaders.csv, suppress.xml
=> improve error logging

pom.xml
Updating spring boot version to fix CVEs
=> Updating spring boot version to fix cve

Makefile, pom.xml
Updating Makefile and pom for new version of Sonarqube
IDVA5-2029
=> Updating Makefile and pom for new version of Sonarqube

src/main/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessor.java
Adding a logger to print the headers received in the file when they are incorrect. Updated toLowerCase to include the language
IDVA5-2032
=> Adding a logger to print the headers received in the file when they are incorrect. Updated toLowerCase to include the language

src/main/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessor.java, suppress.xml
Updating logger messages to show the correct line number and to have consistent wording
IDVA5-2032
=> Updating logger messages to show the correct line number and to have consistent wording

src/main/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessor.java, src/test/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessorTest.java, src/test/resources/good_multiple_records_with_BOM.csv
Checking to see if the BOM char is present at the start of the headers and if so then removing it. Also adding UTF-8 char set to the reader
=> Removing BOM from the headers of CSV file

src/main/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessor.java, src/test/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessorTest.java, src/test/resources/correctHeadersWithBOM.csv, src/test/resources/good_multiple_records_with_BOM.csv
Updating the input stream reader to use BOMInputStream this will ignore the BOM char at the start of the headers
IDVA5-2083
=> Updating the input stream reader to use BOMInputStream

src/main/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessor.java
Updating how the CVS processor gets the headers. This should prevent it checking the headers midway through the file
IDVA5-2203
=> Checking headers using getFirst method to prevent checking twice

src/main/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessor.java
Updating csv parser to ignore the headers when parsing the file. They should now only be tested at the start of reading the file bytes
IDVA5-2203
=> Updating csv parser to ignore the headers when parsing the file

src/main/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessor.java
Updated the CSV processor to no longer separate the headers out from the beginning of the file - as this caused a new bug to occur
IDVA5-2203
=> Updated the CSV processor to no longer separate the headers out from the beginning of the file

src/main/java/uk/gov/companieshouse/filevalidationservice/parser/CsvProcessor.java
Reverting back to BOMInputStream and removing loggers
IDVA5-2203
=> Reverting back to BOMInputStream and removing loggers

terraform/groups/ecs-service/main.tf
=> updated secrets and ecs module

pom.xml
=> Sonar code coverage testing
